version: "3"
services:
    backend:
        image: mounazoghlami/achat-1.0-s7:latest
        ports:
            - "8089:8089"
        restart: unless-stopped
        container_name: spring
        depends_on:
            - sql_db
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://sql_db:3306/tpachat?createDatabaseIfNotExist=true
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root

    sql_db:
        image: mysql:8
        container_name: sql_db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=tpachat
        volumes:
            - "db_volume:/var/lib/mysql"   


volumes:
  db_volume: {}